version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: cqrs-playground
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: cqrs
    ports:
      - "5439:5432"
    networks:
      - postgres-network
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  postgres-network:
    driver: bridge
